### ISSUE TITLE
Bullet to PhysX

### ISSUE THREAD

**Issue by alanjfs** [AIS-Bonn/stillleben#2]
Hi team, found you via Magnum's [latest release notes](https://blog.magnum.graphics/announcements/2020.06/), and it looks like a really interesting project!

I'm also using PhysX for my current projects - having previously evaluated Bullet, ODE, Newton and MuJoCo - and noticed in your commit-history that you were previously using Bullet. I was wondering whether it would be possible to say a few words about that transition, what motivated it and what your thoughts are about it now that you've implemented it?

For me, the choice was between PhysX and Bullet, the decision ultimately coming down to more easily accessible documentation of PhysX, whereby ODE was a little too bare-bone, Newton not having a sizeable enough community and MuJoCo being proprietary.

**Comment by xqms** [comment]
My motivation for switching to PhysX was quite ad-hoc: At the time I had meshes of very questionable quality and experienced a lot of problems with Bullet. Switching to PhysX solved a lot of them immediately. Nowadays I'm using V-HACD, which solves most quality problems in the mesh preprocessing stage. So I'm not sure if that motivation is still valid ;)
I also observed a considerable performance gain, but I never measured that in detail.

My use case is also a bit exotic: I don't care about realistic behavior during simulation, I only want to reach a steady state which is physically plausible. The initial configuration of objects is random anyway.

I share your point about documentation. While PhysX documentation is still not perfect and not well-accessible, it is there and helpful. With Bullet, many details are not documented and you have to dive into the code yourself.

I never evaluated other alternatives like ODE or even DART, since PhysX worked fine.

**Comment by alanjfs** [comment]
Thanks @xqms! That resolves this "issue" for me. :)
