### ISSUE TITLE
Strange table-top simulation result.

### ISSUE THREAD

**Issue by eendru** [AIS-Bonn/stillleben#8]
Hi!
I am tryinng to simulate tabeltop scene.
I have added tote to scene with parameters:
```
tote_obj = sl.Object(self._tote_mesh)
tote_obj.static = True
tote_obj.dynamic_friction = 0.0001
tote_obj.static_friction = 0.5
tote_obj.mass = 5.0
```

Also, I have added the simple object(soap) with parameters:
```
object_on_scene.dynamic_friction = 0.0001
object_on_scene.static_friction = 0.5
object_on_scene.mass = 1.0
```

(I understand that there is no soap in a package weighing 1 kilogram. 1 kg just for illustration)

![color](https://user-images.githubusercontent.com/22100428/194002183-f2cc9227-9fd7-4838-8143-f72feac046d1.png)

What am I doing wrong ? Why is one of the soap object stuck to the side of the wall?

Thanks in advance!

**Comment by xqms** [comment]
Hey, that seems interesting. I assume you used `scene.simulate_tabletop_scene()` to simulate. There might be two reasons for this behavior:

1. There is something wrong with the physics simulation, usually due to strange meshes. You can check this by opening the viewer (`sl.view(scene)`) and enabling the checkbox for drawing physics collision meshes. You can also check the box "run physics" to see if the object can drop down or is stuck to the wall somehow.
2. `simulate_tabletop_scene()` contains some logic for re-dropping objects which fall outside of the static container. It might be that the object was just re-dropped, but `simulate_tabletop_scene()` ran out of time (there is a max iteration limit) to simulate how it should be falling. You should be able to detect such cases by looking at the `linear_velocity` object of each object. If it is above a threshold, it is probably still falling. Another option is to call `scene.simulate()` in a loop after `simulate_tabletop_scene()` exits to make sure that there is sufficient time for objects to drop.

**Comment by eendru** [comment]
>> You should be able to detect such cases by looking at the linear_velocity object of each object. If it is above a threshold, it is probably still falling. 

It looks easy - use container for saving all objects, and check `linear_velocity` of each object.
As I understand, `linear_velocity` values must be near zero.
What should be done if the norm of the `linear_velocity` vector is greater than threshold ? 


P.S.
I dropped two soap object to tote and print `norm` of  `linear_velocity` of each soap object every second. Sometimes it's constant non-zero value.

**Comment by xqms** [comment]
> What should be done if the norm of the linear_velocity vector is greater than threshold ?

That depends on your application. You could remove the object or discard everything and start simulation from scratch.

> I dropped two soap object to tote and print norm of linear_velocity of each soap object every second. Sometimes it's constant non-zero value.

So you are using `simulate()` instead of `simulate_tabletop_scene()`?

**Comment by eendru** [comment]
I am using ` scene.simulate(1.0)` after `simulate_tabletop_scene()`

**Comment by eendru** [comment]
>>That depends on your application. You could remove the object or discard everything and start simulation from scratch.

Oh, I am sorry, my goal is tote full with soap objects.
So, I think, it's better to remove unwanted object, and add again.

**Comment by xqms** [comment]
`scene.simulate()` is meant to be called with small time steps. You should use 0.05 at maximum. Use a loop around it if you want to simulate longer times.

**Comment by eendru** [comment]
Okay,
I tried the following:
1. Add tote to scene with commands: 
```
tote_obj = sl.Object(self._tote_mesh)
tote_obj.static = True
tote_obj.dynamic_friction = 0.0001
tote_obj.static_friction = 0.5
tote_obj.mass = 5.0
```

2. Add 150 soap objects on scene
3. In loop
```
- simulate_tabletop()
- check linear_velocity norms
- if one of norm more than threshold, do simulate(0.05) 20000 times.
   After each simulate() call check_norm() of all velocities.
```
4.  For 150 soap scene only one or two was with small velocities.

How can I improve this ? Remove objects with bad velocities only and add back ? Call `simulate()` more times ?
Can I set the height of throwing objects?

**Comment by xqms** [comment]
If you launch the viewer (`sl.view(scene)`) you can also trigger the tabletop simulation live to see what might be going wrong.

Otherwise, you will have to look at the C++ source of stillleben (`src/scene.cpp`, function `simulateTableTopScene()`). I currently sadly don't have the time to look at your problem in detail. Maybe I will have time in November - but then I will need your exact meshes and complete code.

**Comment by eendru** [comment]
Okay, thank you for your reply.
I am going to remove N bad objects and render scene. Also I will check in viewer.
